# Generated by Django 6.1 on 2026-09-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
