# Generated by Django 6.1 on 2026-09-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
