# Generated by Django 6.1 on 2026-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowrecord_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
