# Generated by Django 6.1 on 2026-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_borrowrecord_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='available',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
