# Generated by Django 6.1 on 2026-09-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_borrowrecord_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'ordering': ['-borrowed_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.book'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('user', 'book'), name='unique_active_borrow_per_user_book'),
        ),
    ]
