# Generated by Django 6.1 on 2026-09-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_sku_3b65b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_categor_471378_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_brand_i_aafe59_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='pos_stock_product_17737f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
