# Generated by Django 6.1 on 2026-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_warehouse'),
        ),
    ]
